-- 0. Tipos de datos personalizados
CREATE TYPE rol_usuario AS ENUM ('admin', 'cliente');

-- 1. Categorías
CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  descripcion TEXT
);

-- 2. Productos (Producto Final)
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  stock_actual INT DEFAULT 0,
  descripcion TEXT,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL
);

CREATE TABLE producto_imagenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE NOT NULL,
  url TEXT NOT NULL,
  es_principal BOOLEAN DEFAULT false,
  orden INT NOT NULL,
  fecha_subida TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Restricción: Un producto no puede tener dos imágenes con el mismo número de orden
  CONSTRAINT unique_producto_orden UNIQUE(producto_id, orden)

    -- Restricción: Un producto no puede tener la misma imagen
  CONSTRAINT unique_producto_url UNIQUE(producto_id, url)
);

-- 3. Ingredientes / Insumos (Lo que se usa para cocinar)
CREATE TABLE ingredientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  unidad_medida TEXT NOT NULL, 
  stock_actual DECIMAL(10,2) DEFAULT 0
);

-- 4. Proveedores
CREATE TABLE proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  contacto_nombre TEXT,
  telefono TEXT,
  email TEXT
);

-- 5. Entradas de Inventario (Registro de compras de ingredientes)
CREATE TABLE entradas_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingrediente_id BIGINT REFERENCES ingredientes(id) ON DELETE CASCADE,
  proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE SET NULL,
  cantidad DECIMAL(10,2) NOT NULL,
  costo_total DECIMAL(10,2),
  fecha_compra TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Perfiles
CREATE TABLE perfiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  rol rol_usuario DEFAULT 'cliente',
  direccion TEXT,
  telefono TEXT NOT NULL,
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Estados del Pedido (Catálogo/Relleno)
CREATE TABLE estados_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE 
);

-- 8. Cupones / Promociones
CREATE TABLE cupones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  descuento_porcentaje INT CHECK (descuento_porcentaje > 0 AND descuento_porcentaje <= 100),
  activo BOOLEAN DEFAULT true,
  fecha_expiracion DATE
);

-- 9. Pedidos
CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id UUID REFERENCES perfiles(id) NOT NULL, -- Relación con el perfil del cliente
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  total DECIMAL(10,2) DEFAULT 0,
  estado_id BIGINT REFERENCES estados_pedido(id) DEFAULT 1,
  cupon_id BIGINT REFERENCES cupones(id) ON DELETE SET NULL
);

-- 10. Detalle de Pedido (Relación Muchos a Muchos entre Pedidos y Productos)
CREATE TABLE detalle_pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
  producto_id BIGINT REFERENCES productos(id),
  cantidad INT NOT NULL,
  precio_unitario_historico DECIMAL(10,2) NOT NULL 
);